language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get install -y xsltproc pandoc
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F3E07576
  - sudo add-apt-repository 'deb [arch=amd64] http://sparkl.release.s3.amazonaws.com xenial main'
  - sudo apt-get update
  - sudo apt-get install -y sparkl
script: make lint compile
