language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get install -y xsltproc pandoc
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C58A47E1
  - sudo add-apt-repository 'deb [arch=amd64] http://sparkl.release.s3.amazonaws.com xenial main'
  - sudo apt-get update
  - sudo apt-get install -y sse
script:
  - make lint compile
  - sse start ./sse1
  - sleep 5
  - python -m sparkl_cli connect http://localhost:8000
  - echo password | python -m sparkl_cli login -r test@localhost password
  - TEST_SSE=http://localhost:8000 TEST_USER=test@localhost TEST_PASS=password make test
